"""Initial database schema

Revision ID: a393cdbc59be
Revises: 
Create Date: 2025-11-09 20:08:56.019736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a393cdbc59be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.String(length=20), nullable=True),
    sa.Column('company_logo_url', sa.String(length=500), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('skills_required', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_job_matching', 'jobs', ['match_score', 'is_active', 'scraped_at'], unique=False)
    op.create_index('idx_job_search', 'jobs', ['title', 'company', 'location'], unique=False)
    op.create_index('idx_job_source', 'jobs', ['source', 'scraped_at'], unique=False)
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    op.create_index(op.f('ix_jobs_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('ix_jobs_match_score'), 'jobs', ['match_score'], unique=False)
    op.create_index(op.f('ix_jobs_scraped_at'), 'jobs', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('target_titles', sa.Text(), nullable=True),
    sa.Column('target_locations', sa.Text(), nullable=True),
    sa.Column('target_companies', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('excluded_keywords', sa.Text(), nullable=True),
    sa.Column('min_salary', sa.String(length=50), nullable=True),
    sa.Column('max_salary', sa.String(length=50), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('work_type_preference', sa.String(length=50), nullable=True),
    sa.Column('job_type_preference', sa.String(length=50), nullable=True),
    sa.Column('min_experience_years', sa.String(length=50), nullable=True),
    sa.Column('max_experience_years', sa.String(length=50), nullable=True),
    sa.Column('max_applications_per_day', sa.String(length=50), nullable=True),
    sa.Column('min_match_score', sa.String(length=50), nullable=True),
    sa.Column('auto_apply_enabled', sa.Boolean(), nullable=True),
    sa.Column('require_manual_approval', sa.Boolean(), nullable=True),
    sa.Column('preferred_ai_model', sa.String(length=50), nullable=True),
    sa.Column('resume_tone', sa.String(length=50), nullable=True),
    sa.Column('tailoring_aggressiveness', sa.String(length=50), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('notification_frequency', sa.String(length=50), nullable=True),
    sa.Column('notify_on_response', sa.Boolean(), nullable=True),
    sa.Column('notify_on_interview', sa.Boolean(), nullable=True),
    sa.Column('total_applications', sa.String(length=50), nullable=True),
    sa.Column('total_responses', sa.String(length=50), nullable=True),
    sa.Column('total_interviews', sa.String(length=50), nullable=True),
    sa.Column('total_offers', sa.String(length=50), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.String(length=50), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_activity', 'users', ['last_activity_at'], unique=False)
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('based_on_resume_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('resume_type', sa.Enum('BASE', 'TAILORED', 'TEMPLATE', name='resume_type'), nullable=False),
    sa.Column('file_format', sa.Enum('PDF', 'DOCX', 'TXT', name='resume_format'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('storage_provider', sa.String(length=50), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('tailored_for_title', sa.String(length=255), nullable=True),
    sa.Column('tailored_for_company', sa.String(length=255), nullable=True),
    sa.Column('tailoring_prompt', sa.Text(), nullable=True),
    sa.Column('tailoring_model', sa.String(length=100), nullable=True),
    sa.Column('changes_made', sa.Text(), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('template_style', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.String(length=50), nullable=True),
    sa.Column('views', sa.String(length=50), nullable=True),
    sa.Column('downloads', sa.String(length=50), nullable=True),
    sa.Column('success_rate', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['based_on_resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resume_job', 'resumes', ['job_id'], unique=False)
    op.create_index('idx_resume_user_type', 'resumes', ['user_id', 'resume_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_resumes_is_active'), 'resumes', ['is_active'], unique=False)
    op.create_index(op.f('ix_resumes_resume_type'), 'resumes', ['resume_type'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'VIEWED', 'REJECTED', 'INTERVIEW', 'OFFER', 'ACCEPTED', 'DECLINED', 'WITHDRAWN', name='application_status'), nullable=False),
    sa.Column('resume_version', sa.String(length=255), nullable=True),
    sa.Column('cover_letter_version', sa.String(length=255), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('response_received_at', sa.DateTime(), nullable=True),
    sa.Column('interview_date', sa.DateTime(), nullable=True),
    sa.Column('response_received', sa.Boolean(), nullable=True),
    sa.Column('response_type', sa.String(length=50), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('application_method', sa.String(length=50), nullable=True),
    sa.Column('confirmation_number', sa.String(length=255), nullable=True),
    sa.Column('portal_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('automated', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_date', sa.DateTime(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('submission_data', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_application_job', 'applications', ['job_id', 'status'], unique=False)
    op.create_index('idx_application_status_date', 'applications', ['status', 'applied_at'], unique=False)
    op.create_index('idx_application_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_applications_applied_at'), 'applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_response_received'), 'applications', ['response_received'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_response_received'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_applied_at'), table_name='applications')
    op.drop_index('idx_application_user_status', table_name='applications')
    op.drop_index('idx_application_status_date', table_name='applications')
    op.drop_index('idx_application_job', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_resume_type'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_is_active'), table_name='resumes')
    op.drop_index('idx_resume_user_type', table_name='resumes')
    op.drop_index('idx_resume_job', table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_index('idx_user_activity', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scraped_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_match_score'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_location'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_index('idx_job_source', table_name='jobs')
    op.drop_index('idx_job_search', table_name='jobs')
    op.drop_index('idx_job_matching', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
