"""Add agent system tables and fields

Revision ID: ce447d3f9068
Revises: a393cdbc59be
Create Date: 2025-11-09 21:37:49.294478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce447d3f9068'
down_revision = 'a393cdbc59be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_summary', sa.String(length=500), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('collection_name', sa.String(length=100), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_embedding', 'agent_memory', ['collection_name', 'embedding_id'], unique=False)
    op.create_index('idx_memory_type_score', 'agent_memory', ['memory_type', 'relevance_score'], unique=False)
    op.create_index('idx_memory_usage', 'agent_memory', ['usage_count', 'last_used_at'], unique=False)
    op.create_index(op.f('ix_agent_memory_embedding_id'), 'agent_memory', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_agent_memory_memory_type'), 'agent_memory', ['memory_type'], unique=False)
    op.create_table('approval_requests',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval_token', sa.String(length=255), nullable=False),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('agent_reasoning', sa.Text(), nullable=True),
    sa.Column('match_score', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_expires', 'approval_requests', ['expires_at', 'status'], unique=False)
    op.create_index('idx_approval_user_status', 'approval_requests', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_approval_requests_application_id'), 'approval_requests', ['application_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_approval_token'), 'approval_requests', ['approval_token'], unique=True)
    op.create_index(op.f('ix_approval_requests_expires_at'), 'approval_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_job_id'), 'approval_requests', ['job_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_sent_at'), 'approval_requests', ['sent_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_approval_requests_user_id'), 'approval_requests', ['user_id'], unique=False)
    op.create_table('agent_learning',
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_success', 'agent_learning', ['agent_type', 'success_rate'], unique=False)
    op.create_index('idx_agent_type_metric', 'agent_learning', ['agent_type', 'metric_name'], unique=False)
    op.create_index('idx_agent_user', 'agent_learning', ['user_id', 'agent_type'], unique=False)
    op.create_index(op.f('ix_agent_learning_agent_type'), 'agent_learning', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_learning_metric_name'), 'agent_learning', ['metric_name'], unique=False)
    op.create_index(op.f('ix_agent_learning_user_id'), 'agent_learning', ['user_id'], unique=False)
    op.create_table('feedback_loop',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('outcome_timestamp', sa.DateTime(), nullable=True),
    sa.Column('response_time_days', sa.String(length=50), nullable=True),
    sa.Column('response_quality', sa.String(length=20), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strategy_adjustments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_notes', sa.Text(), nullable=True),
    sa.Column('pattern_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_outcome', 'feedback_loop', ['outcome', 'outcome_timestamp'], unique=False)
    op.create_index(op.f('ix_feedback_loop_application_id'), 'feedback_loop', ['application_id'], unique=True)
    op.create_index(op.f('ix_feedback_loop_outcome'), 'feedback_loop', ['outcome'], unique=False)
    op.create_index(op.f('ix_feedback_loop_outcome_timestamp'), 'feedback_loop', ['outcome_timestamp'], unique=False)
    op.add_column('applications', sa.Column('agent_reasoning', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('applied_by_agent', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('approval_request_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'applications', 'approval_requests', ['approval_request_id'], ['id'], ondelete='SET NULL')
    op.add_column('jobs', sa.Column('agent_evaluated', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('agent_recommendation', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('scraped_by_agent', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_jobs_agent_evaluated'), 'jobs', ['agent_evaluated'], unique=False)
    op.add_column('resumes', sa.Column('performance_score', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('response_rate', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('interview_rate', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('last_performance_update', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('agent_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('last_agent_run', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('learning_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('approval_timeout_hours', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'approval_timeout_hours')
    op.drop_column('users', 'learning_enabled')
    op.drop_column('users', 'last_agent_run')
    op.drop_column('users', 'agent_status')
    op.drop_column('resumes', 'last_performance_update')
    op.drop_column('resumes', 'interview_rate')
    op.drop_column('resumes', 'response_rate')
    op.drop_column('resumes', 'performance_score')
    op.drop_index(op.f('ix_jobs_agent_evaluated'), table_name='jobs')
    op.drop_column('jobs', 'scraped_by_agent')
    op.drop_column('jobs', 'agent_recommendation')
    op.drop_column('jobs', 'agent_evaluated')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'approval_request_id')
    op.drop_column('applications', 'applied_by_agent')
    op.drop_column('applications', 'agent_reasoning')
    op.drop_index(op.f('ix_feedback_loop_outcome_timestamp'), table_name='feedback_loop')
    op.drop_index(op.f('ix_feedback_loop_outcome'), table_name='feedback_loop')
    op.drop_index(op.f('ix_feedback_loop_application_id'), table_name='feedback_loop')
    op.drop_index('idx_feedback_outcome', table_name='feedback_loop')
    op.drop_table('feedback_loop')
    op.drop_index(op.f('ix_agent_learning_user_id'), table_name='agent_learning')
    op.drop_index(op.f('ix_agent_learning_metric_name'), table_name='agent_learning')
    op.drop_index(op.f('ix_agent_learning_agent_type'), table_name='agent_learning')
    op.drop_index('idx_agent_user', table_name='agent_learning')
    op.drop_index('idx_agent_type_metric', table_name='agent_learning')
    op.drop_index('idx_agent_success', table_name='agent_learning')
    op.drop_table('agent_learning')
    op.drop_index(op.f('ix_approval_requests_user_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_sent_at'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_job_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_expires_at'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_approval_token'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_application_id'), table_name='approval_requests')
    op.drop_index('idx_approval_user_status', table_name='approval_requests')
    op.drop_index('idx_approval_expires', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_agent_memory_memory_type'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_embedding_id'), table_name='agent_memory')
    op.drop_index('idx_memory_usage', table_name='agent_memory')
    op.drop_index('idx_memory_type_score', table_name='agent_memory')
    op.drop_index('idx_memory_embedding', table_name='agent_memory')
    op.drop_table('agent_memory')
    # ### end Alembic commands ###
